### ISSUE TITLE
explain me why i only hear of this now

### ISSUE THREAD

**Issue by ExtReMLapin** [glua/propwalking#1]
explain

**Comment by ExtReMLapin** [comment]
#EXPLAIN

**Comment by Jvs34** [comment]
cause ur a fag

**Comment by ExtReMLapin** [comment]
\>name is Alessio

\>call others fag

**Comment by Jvs34** [comment]
>literally baguette

![image](https://cloud.githubusercontent.com/assets/1412812/26737211/793c8d54-47c9-11e7-803e-7dd5d34243d7.png)

**Comment by ExtReMLapin** [comment]
![](http://i.imgur.com/bt42pME.jpg)

**Comment by Kefta** [comment]
hm
